services:
  - docker:dind

stages:
  - image
  - build
  - package
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker-image:
  stage: image
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

.build: &build
  stage: build
  script:
    - bash .ci/build.sh
  artifacts:
    paths:
    - ci-out/

armeabi-v7a:
  <<: *build
  variables:
    TARGET_ARCH: armeabi-v7a

arm64-v8a:
  <<: *build
  variables:
    TARGET_ARCH: arm64-v8a

x86:
  <<: *build
  variables:
    TARGET_ARCH: x86
  allow_failure: true

x86-64:
  <<: *build
  variables:
    TARGET_ARCH: x86_64
  allow_failure: true

package:
  stage: package
  script:
    - ./.ci/package.sh
  only:
    - master
  artifacts:
    paths:
    - package/

release-nightly:
  stage: release
  script:
  - /bin/true
  only:
  - master

release-production:
  stage: release
  script:
  - /bin/true
  only:
  - tags
  except:
  - branches
  when: manual
