build:
  stage: build
  commands:
    - bash .ci/bind-cache.sh
    - export DISABLE_PROGRESS=1
    - 'echo -e "EXEC=docker\nDOCKER_IMAGE=kivy\nDISABLE_PROGRESS=1" > .env'
    - make docker-build
    - bash ./tool.sh prebuild
    - make _ci
